# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LLKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LLKit
  pod 'YYModel', '~> 1.0.4'
  pod 'IGListKit', '~> 3.4.0'

end
